name: update

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-24.04
    steps:
      - uses: cachix/install-nix-action@v30
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          persist-credentials: false
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: Update grammars
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config --local user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --local user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
          git config --local url."https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/".pushInsteadOf "https://github.com/"

          nix develop -c python update.py -o lib/sources.nix
          if ! git diff --quiet lib/sources.nix; then
            git commit -m "Update grammars" lib/sources.nix
            git push
          fi

          git config --local --remove-section url."https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/"
